### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by GUNASEKARsekar** [secret-sahil/iic-ikgptu-certificate#1]
Admin username and password

**Comment by secret-sahil** [comment]
Username: admin@ptu.ac.in
Password: admin

**Comment by GUNASEKARsekar** [comment]
Thank You

**Comment by secret-sahil** [comment]
Welcome! If it will not work let me know I'll give you a new **SQL** DB file.

**Comment by GUNASEKARsekar** [comment]
ok.. please give a new sql file

**Comment by secret-sahil** [comment]
admin/include/db-samle.php Check this file. I have fixed the issue.
If you face any issues you can contact me on discord: https://dsc.gg/mrsahil

**Comment by GUNASEKARsekar** [comment]
Thanks
