### ISSUE TITLE
variable db is not found 

### ISSUE THREAD

**Issue by GUNASEKARsekar** [secret-sahil/iic-ikgptu-certificate#2]
Notice: Undefined variable: db in C:\xampp\htdocs\iic-ikgptu-certificate-master\admin\index.php on line 38

Fatal error: Uncaught Error: Call to a member function prepare() on null in C:\xampp\htdocs\iic-ikgptu-certificate-master\admin\index.php:38 Stack trace: #0 {main} thrown in C:\xampp\htdocs\iic-ikgptu-certificate-master\admin\index.php on line 38

how to clear the error.. I will try more times... please help me .

**Comment by secret-sahil** [comment]
admin/include/db-samle.php Check this file. I have fixed the issue.
If you face any issues you can contact me on discord: https://dsc.gg/mrsahil
