### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by GUNASEKARsekar** [secret-sahil/iic-ikgptu-certificate#3]
the email username and password is not working
wrong email or password

**Comment by secret-sahil** [comment]
admin/include/db-samle.php Check this file. I have fixed the issue.
If you face any issues you can contact me on discord: https://dsc.gg/mrsahil

**Comment by seyidturgut** [comment]
The given password is incorrect

correct password enc. In this way, the admin gives the answer.

But even if you fix this, the admin page does not work. nothing is working



db admin table password change = $1$bag2uLPk$Xad6v7dn7UGuh916fsULr/
enc = admin

**Comment by secret-sahil** [comment]
Fixed everything. Delete the old database and install the new one and follow the instruction in the Readme file. Thanks
